name: Boy_flow
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.3.2
  permission_handler: ^12.0.1
  video_player: ^2.8.2
  dotted_border: ^3.1.0
  url_launcher: ^6.2.5
  intl: ^0.20.2
  share_plus: ^12.0.0
  cupertino_icons: ^1.0.8
  agora_rtc_engine: ^6.3.2
  flutter_callkit_incoming: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile_account.png
    - assets/male_avatar.png
    - assets/img_1.png
    - assets/vector.png
    - assets/female_avatar.png
    # - assets/girls.png
    # - assets/girl2.png
    - assets/girls.png
    - assets/girl2.png
    - assets/LoginImage.png
    - assets/Otp.png
    - assets/Signup.png
    - assets/verificationsuccess.png
    - assets/coins.png
    - assets/login.png
    - assets/splashimage.png
    - assets/failed_icon.png
    - assets/Registration.png
    - assets/wallet.png
    - assets/profile.png
    - assets/earnings.png
    - assets/settings.png
    - assets/Notifications.png
    - assets/invite_illustration.png
    - assets/cash.png
    - assets/withdraw.png
    - assets/sheild.png
    - assets/user1.png
    - assets/user2.png
    - assets/youtube.png
    - assets/callrate.png
    - assets/profile&gallery.png
    - assets/followers.png
    - assets/supportservice.png
# If you plan to add fonts, uncomment and configure the fonts section
# fonts:
#   - family: Poppins
#     fonts:
#       - asset: assets/fonts/Poppins-Regular.ttf
#       - asset: assets/fonts/Poppins-Bold.ttf
#         weight: 700
#       - asset: assets/fonts/Poppins-Italic.ttf
#         style: italic
